URL = "http://10.13.8.6:2222/index.php"
CORE_NB = 8
header = """
    __                _          ____             __          ______                   
   / /   ____  ____ _(_)___     / __ )_______  __/ /____     / ____/___  _____________ 
  / /   / __ \/ __ `/ / __ \   / __  / ___/ / / / __/ _ \   / /_  / __ \/ ___/ ___/ _ \\
 / /___/ /_/ / /_/ / / / / /  / /_/ / /  / /_/ / /_/  __/  / __/ / /_/ / /  / /__/  __/
/_____/\____/\__, /_/_/ /_/  /_____/_/   \__,_/\__/\___/  /_/    \____/_/   \___/\___/ 
            /____/                                                                     

"""

usernames = (
    "admin",
    "user",
    "test",
    "guest",
    "root",
    "administrator",
    "demo",
    "info",
    "webmaster",
    "support",
    "manager",
    "sysadmin",
    "office",
    "sales",
    "contact",
    "help",
    "service",
    "marketing",
    "team",
    "account",
    "student",
    "developer",
    "staff",
    "security",
    "operator",
    "qa",
    "tester",
    "client",
    "public",
    "reception",
)
passwords = (
    "!@#$%^&*",
    "000000",
    "111111",
    "121212",
    "123123",
    "1234",
    "12345",
    "123456",
    "1234567",
    "12345678",
    "123456789",
    "1234567890",
    "123qwe",
    "1q2w3e4r",
    "1qaz2wsx",
    "555555",
    "654321",
    "666666",
    "696969",
    "7777777",
    "888888",
    "Football",
    "aa123456",
    "abc123",
    "access",
    "admin",
    "adobe123[a]",
    "ashley",
    "azerty",
    "bailey",
    "baseball",
    "batman",
    "charlie",
    "donald",
    "dragon",
    "flower",
    "football",
    "freedom",
    "hello",
    "hottie",
    "iloveyou",
    "jesus",
    "letmein",
    "login",
    "lovely",
    "loveme",
    "master",
    "michael",
    "monkey",
    "mustang",
    "ninja",
    "passw0rd",
    "password",
    "password1",
    "photoshop[a]",
    "princess",
    "qazwsx",
    "qwerty",
    "qwerty123",
    "qwertyuiop",
    "shadow",
    "solo",
    "starwars",
    "sunshine",
    "superman",
    "trustno1",
    "welcome",
    "whatever",
    "zaq1zaq1",
)
